// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Fmm5xCzBP4KfjEAISr-zPRmt7Mfh8Vc',
    appId: '1:841559049:web:9c15687cdd306694f0dcd8',
    messagingSenderId: '841559049',
    projectId: 'cw03-task-manager',
    authDomain: 'cw03-task-manager.firebaseapp.com',
    storageBucket: 'cw03-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRPo_fcCH-HSLr5hg7KA3UR1wVmVfTDnE',
    appId: '1:841559049:android:544bd48997bb2f31f0dcd8',
    messagingSenderId: '841559049',
    projectId: 'cw03-task-manager',
    storageBucket: 'cw03-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVsiG4AkWVYw6laKT2wowy56hAjvFa8E',
    appId: '1:841559049:ios:6b17190fe794fb3bf0dcd8',
    messagingSenderId: '841559049',
    projectId: 'cw03-task-manager',
    storageBucket: 'cw03-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVsiG4AkWVYw6laKT2wowy56hAjvFa8E',
    appId: '1:841559049:ios:6b17190fe794fb3bf0dcd8',
    messagingSenderId: '841559049',
    projectId: 'cw03-task-manager',
    storageBucket: 'cw03-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Fmm5xCzBP4KfjEAISr-zPRmt7Mfh8Vc',
    appId: '1:841559049:web:528ef84f1bb38a39f0dcd8',
    messagingSenderId: '841559049',
    projectId: 'cw03-task-manager',
    authDomain: 'cw03-task-manager.firebaseapp.com',
    storageBucket: 'cw03-task-manager.firebasestorage.app',
  );
}
